name: Настройка подписи APK

# Это опциональный workflow, который можно будет использовать позже
# для настройки подписи APK с использованием секретов GitHub

on:
  workflow_dispatch:  # Ручной запуск

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v3
      
      # Пример, как декодировать keystore из секретов
      - name: Декодирование keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore
        
      # Пример создания файла gradle.properties с секретами для подписи
      - name: Создание gradle.properties с секретами
        run: |
          cat > android/gradle.properties << EOF
          MYAPP_UPLOAD_STORE_FILE=my-release-key.keystore
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF
